name: crop_capture
description: Mini Project for Mobile Application Development

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7
  tflite: ^1.1.2
  image: ^4.0.15
  path_provider: ^2.0.13
  flutter_svg: ^2.0.4
  lottie: ^2.3.0
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/model/SequentialModel_v3.tflite
    - assets/model/labels.txt
    - assets/images/Empty_place_Holder.png
    - assets/images/profile.png
    - assets/icons/leaf_icon.json
    - assets/icons/happy_plant.json
    - assets/icons/no_images.json
