// ignore_for_file: constant_identifier_names

import 'package:crop_capture/model/plant.dart';

const PLANT_DETAILS = [
  Plant(
    index: 1,
    name: "Corn",
    disease: "Cercospora Leaf Spot",
    type: "Fungal Disease",
    pathogen: "Cercospora zeae-maydis",
    symptoms: [
      "Small, circular to elongated grayish-green lesions on the lower leaves of the plant",
      "Lesions can range in size from 1 to 2 mm and can be surrounded by a yellow halo",
      "Lesions will become larger and turn brown or gray with a tan center",
      "Lesions may merge together, causing significant damage to the foliage and leading to premature leaf death",
      "Lesions can also appear on the husks of the ears, reducing grain quality and yield",
      "Stunted growth, reduced yield, and an increased susceptibility to other diseases and pests",
    ],
    remedies: [
      "Crop Rotation: Cercospora zeae-maydis can survive in infected plant debris in the soil, so rotating crops can help break the disease cycle.",
      "Fungicides: Applying fungicides can help control the disease, but they should be used as a last resort and only when necessary.",
      "Resistant Varieties: Planting resistant varieties of corn can be an effective way to prevent Cercospora leaf spot disease.",
      "Proper Crop Management: Good crop management practices such as proper irrigation, nutrient management, and weed control can help reduce the severity of the disease.",
      "Sanitation: Removing infected plant debris and destroying it can help reduce the spread of the disease.",
      "Early Detection: Regular scouting and monitoring can help detect the disease early, which can make it easier to manage,It's also important to remove and destroy infected plant debris to prevent the spread of the disease to healthy plants.",
    ],
  ),
  Plant(
    index: 3,
    name: "Corn",
    disease: "Northern Leaf Blight",
    type: "Fungal Disease",
    pathogen: "Setosphaeria turcica",
    symptoms: [
      "Cigar-shaped, gray-green lesions on leaves with yellow or brown borders",
      "Lesions tend to start on lower leaves and move up the plant",
      "In severe cases, lesions can merge together and kill entire leaves",
      "Yield loss and reduced grain quality can occur",
    ],
    remedies: [
      "Plant Resistant Varieties: Plant corn varieties that are resistant to northern leaf blight.",
      "Crop Rotation: Rotate corn crops with non-host crops to break the disease cycle and reduce the amount of inoculum in the soil.",
      "Fungicides: Apply fungicides preventively, especially during periods of high humidity and rainfall.",
      "Tillage and Sanitation: Till infected crop debris into the soil and avoid planting corn in the same field for at least one year. Remove and destroy crop debris at the end of the season to reduce the amount of inoculum for the next season.",
      "Monitoring: Regularly monitor corn crops for signs of northern leaf blight, especially during periods of high humidity and rainfall. Early detection can help prevent the disease from spreading and causing significant damage.",
      "Balanced Nutrition: Providing balanced nutrition to the corn plants can help improve their overall health and resilience against diseases.",
    ],
  ),
  Plant(
    index: 4,
    name: "Cotton",
    disease: "Aphids",
    type: "Biotic disease",
    pathogen: "Pear-shaped Insects",
    symptoms: [
      "Stunted plant growth.",
      "Yellowing of leaves.",
      "Curling or distortion of leaves.",
      "Presence of sticky, sugary substance (honeydew) on leaves, which can lead to the growth of sooty mold.",
      "Presence of the aphids themselves on the undersides of leaves.",
    ],
    remedies: [
      "Biological control: Encourage natural enemies of cotton aphids, such as lady beetles, lacewings, and parasitic wasps, by planting companion plants and avoiding broad-spectrum insecticides that can harm beneficial insects.",
      "Insecticidal soap: Apply insecticidal soap to the undersides of leaves to kill aphids. Be sure to follow label instructions and use appropriate safety precautions.",
      "Neem oil: Apply neem oil to the undersides of leaves to kill aphids. Be sure to follow label instructions and use appropriate safety precautions.",
      "Horticultural oil: Apply horticultural oil to the undersides of leaves to suffocate aphids. Be sure to follow label instructions and use appropriate safety precautions.",
      "Cultural practices: Avoid over-fertilizing with nitrogen, as this can promote aphid populations. Use drip irrigation instead of overhead irrigation to avoid creating humid conditions that can promote aphid populations.",
    ],
  ),
  Plant(
    index: 5,
    name: "Cotton",
    disease: "Army Worm",
    type: "Biotic disease",
    pathogen: "Moth Species",
    symptoms: [
      "Holes in leaves and buds.",
      "Defoliation of plants.",
      "Presence of small greenish-brown caterpillars with light stripes on the sides of the body.",
      "Presence of adult moths, which are brown or gray with a wingspan of about 1-1.5 inches.",
    ],
    remedies: [
      "Biological control: Encourage natural enemies of cotton armyworms, such as parasitic wasps, predatory bugs, and birds, by planting companion plants and avoiding broad-spectrum insecticides that can harm beneficial insects.",
      "Bacillus thuringiensis (Bt): Apply Bt to the undersides of leaves to kill caterpillars. Bt is a naturally occurring soil bacterium that produces a protein toxic to caterpillars. Be sure to follow label instructions and use appropriate safety precautions.",
      "Insecticides: Apply insecticides to control caterpillar populations. Be sure to follow label instructions and use appropriate safety precautions.",
      "Cultural practices: Rotate crops to reduce the likelihood of armyworm infestations. Maintain good weed control to eliminate alternative hosts for armyworms. Avoid over-fertilizing with nitrogen, which can promote armyworm populations",
    ],
  ),
  Plant(
    index: 6,
    name: "Cotton",
    disease: "Bacterial Blight",
    type: "Bacterial Disease",
    pathogen: "bacterium Xanthomonas citri subsp.malvacearum",
    symptoms: [
      "Water-soaked lesions on the leaves that turn brown or black and become angular in shape.",
      "Lesions may be surrounded by a yellow halo.",
      "Lesions may merge to form larger areas of necrosis.",
      "Infection can spread to other parts of the plant, causing wilt and death of the plant.",
      "The disease is more severe in warm, humid weather.",
    ],
    remedies: [
      "Plant resistant varieties: There are some cotton varieties that have been bred for resistance to bacterial blight.",
      "Crop rotation: Rotate cotton with non-host crops to reduce the buildup of bacteria in the soil.",
      "Sanitation: Remove and destroy infected plants to prevent the spread of the disease.",
      "Chemical control: Copper-based bactericides can be used to control bacterial blight, but they must be applied preventively and may have negative impacts on beneficial bacteria in the soil.",
      "Cultural practices: Avoid overhead irrigation, as this can promote the spread of the disease. Use drip irrigation instead. Also, avoid working in the field when plants are wet to prevent spreading the disease.",
    ],
  ),
  Plant(
    index: 8,
    name: "Cotton",
    disease: "Powdery Mildew",
    type: "Fungal Disease",
    pathogen: "Species of the genus Erysiphe",
    symptoms: [
      "A white, powdery growth on the leaves, stems, and flowers of the plant.",
      "Infected leaves may become distorted and turn yellow or brown.",
      "Infected leaves may curl or distort, which can lead to reduced photosynthesis and lower yields.",
      "As the disease progresses, infected leaves may develop necrotic areas or brown spots, which can eventually lead to leaf drop.",
      "Severe infections can cause stunted growth and reduced yield, as the plant's ability to produce energy through photosynthesis is reduced.",
      "Powdery mildew can also affect the quality of the cotton fibers, leading to lower prices and reduced profits for growers.",
    ],
    remedies: [
      "Plant resistant varieties: There are some cotton varieties that have been bred for resistance to powdery mildew.",
      "Crop rotation: Rotate cotton with non-host crops to reduce the buildup of fungal spores in the soil.",
      "Sanitation: Remove and destroy infected plant material to prevent the spread of the disease.",
      "Fungicides: Apply fungicides early in the season to prevent the disease from becoming established. Be sure to follow label instructions and use appropriate safety precautions.",
      "Cultural practices: Avoid overhead irrigation, as this can promote the spread of the disease. Use drip irrigation instead. Also, avoid working in the field when plants are wet to prevent spreading the disease.",
    ],
  ),
  Plant(
    index: 9,
    name: "Grape",
    disease: "Black Rot",
    type: "Fungal Disease",
    pathogen: "Guignardia bidwellii",
    symptoms: [
      "Small, circular lesions on the leaves, stems, and fruit of the grapevine.",
      "As the disease progresses, the lesions enlarge and turn brown or black.",
      "Infected fruit may become mummified and fall from the vine.",
      "The disease is most common in warm, humid weather.",
    ],
    remedies: [
      "Pruning: Prune out infected plant material and remove fallen fruit from the ground to reduce the spread of the disease.",
      "Sanitation: Remove and destroy infected plant material to prevent the spread of the disease.",
      "Fungicides: Apply fungicides preventatively to control the disease. Be sure to follow label instructions and use appropriate safety precautions.",
      "Cultural practices: Avoid overhead irrigation, as this can promote the spread of the disease. Use drip irrigation instead. Also, avoid working in the vineyard when plants are wet to prevent spreading the disease.",
    ],
  ),
  Plant(
    index: 11,
    name: "Grape",
    disease: "Leaf Blight",
    type: "Fungal Disease",
    pathogen: "Isariopsis griseola",
    symptoms: [
      "Small, circular to angular spots on the leaves, which can be gray or brown in color.",
      "The spots may be surrounded by a yellow halo.",
      "As the disease progresses, the spots may coalesce and cover larger areas of the leaf.",
      "Severe infections can cause premature defoliation.",
    ],
    remedies: [
      "Sanitation: Remove and destroy infected plant material to prevent the spread of the disease.",
      "Fungicides: Apply fungicides preventatively to control the disease. Be sure to follow label instructions and use appropriate safety precautions.",
      "Cultural practices: Promote good air circulation around the vines by pruning and trellising, as this can help to reduce humidity and slow the spread of the disease. Also, avoid overhead irrigation, as this can promote the spread of the disease.",
      "Resistant cultivars: Some grape varieties are more resistant to leaf blight than others. Choosing resistant varieties can be an effective long-term strategy for managing the disease.",
    ],
  ),
  Plant(
    index: 12,
    name: "Potato",
    disease: "Early Blight",
    type: "Fungal Disease",
    pathogen: "Alternaria solani",
    symptoms: [
      "Small, brown lesions with concentric rings develop on older leaves first.",
      "Lesions may coalesce and cause the leaves to turn yellow and die.",
      "Black, sunken spots may appear on stems.",
      "Yield reduction due to premature defoliation.",
    ],
    remedies: [
      "Sanitation: Remove and destroy infected plant material to prevent the spread of the disease.",
      "Fungicides: Apply fungicides preventatively to control the disease. Be sure to follow label instructions and use appropriate safety precautions.",
      "Crop rotation: Rotate potatoes with non-solanaceous crops (e.g. legumes, cereals, grasses) to reduce the build-up of pathogen inoculum in the soil.",
      "Cultural practices: Avoid overhead irrigation, as this can promote the spread of the disease. Prune lower leaves to improve air circulation and reduce humidity, which can slow the spread of the disease. Avoid over-fertilizing with nitrogen, which can make plants more susceptible to the disease.",
      "Resistant varieties: Some potato varieties are more resistant to early blight than others. Choosing resistant varieties can be an effective long-term strategy for managing the disease.",
    ],
  ),
  Plant(
    index: 14,
    name: "Potato",
    disease: "Late Blight",
    type: "Fungal Disease",
    pathogen: "Phytophthora infestan",
    symptoms: [
      "Dark brown to black lesions with irregular margins develop on leaves.",
      "Lesions can rapidly spread to cover entire leaves and stems.",
      "A white, fuzzy mold may be visible on the undersides of leaves during periods of high humidity.",
      "Infected tubers may have a reddish-brown discoloration under the skin and a granular texture.",
    ],
    remedies: [
      "Sanitation: Remove and destroy infected plant material to prevent the spread of the disease.",
      "Fungicides: Apply fungicides preventatively to control the disease. Be sure to follow label instructions and use appropriate safety precautions. Fungicides may need to be applied at shorter intervals during periods of high disease pressure.",
      "Cultural practices: Avoid overhead irrigation, as this can promote the spread of the disease. Prune lower leaves to improve air circulation and reduce humidity, which can slow the spread of the disease. Avoid over-fertilizing with nitrogen, which can make plants more susceptible to the disease.",
      "Resistant varieties: Some potato varieties are more resistant to late blight than others. Choosing resistant varieties can be an effective long-term strategy for managing the disease.",
      "It is important to note that late blight can be difficult to control once it becomes established in a field. Early detection and prompt action are essential for preventing the disease from spreading. Integrated management strategies that combine multiple approaches are most likely to be successful in controlling the disease.",
    ],
  ),
];
